# Generated by Django 5.2.16 on 2026-09-29 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Meat & Poultry', 'Meat & Poultry'), ('Grains & Bread', 'Grains & Bread'), ('Sauces & Spices', 'Sauces & Spices'), ('Beverages', 'Beverages'), ('Packaging', 'Packaging'), ('Other', 'Other')], default='Vegetables', max_length=50)),
                ('unit', models.CharField(help_text='e.g. kg, g, L, ml, pcs, slices', max_length=20)),
                ('current_quantity', models.FloatField(default=0.0)),
                ('min_stock_level', models.FloatField(default=10.0)),
                ('max_stock_level', models.FloatField(default=100.0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Burgers', 'Burgers'), ('Pizzas', 'Pizzas'), ('Sides', 'Sides'), ('Beverages', 'Beverages'), ('Desserts', 'Desserts'), ('Combos', 'Combos')], default='Burgers', max_length=50)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Stock Purchase (In)'), ('USAGE', 'Ingredient Usage (Out)'), ('WASTAGE', 'Wastage Deduction'), ('ADJUSTMENT', 'Stock Adjustment')], max_length=20)),
                ('quantity', models.FloatField()),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory_predictor.ingredient')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemandPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField()),
                ('predicted_quantity', models.IntegerField()),
                ('actual_quantity', models.IntegerField(blank=True, null=True)),
                ('weather_condition', models.CharField(default='Sunny', max_length=30)),
                ('is_holiday', models.BooleanField(default=False)),
                ('special_event', models.CharField(default='None', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='inventory_predictor.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_sold', models.IntegerField()),
                ('day_of_week', models.IntegerField(help_text='0=Monday, 6=Sunday')),
                ('month', models.IntegerField(help_text='1=Jan, 12=Dec')),
                ('is_holiday', models.BooleanField(default=False)),
                ('weather_condition', models.CharField(choices=[('Sunny', 'Sunny'), ('Rainy', 'Rainy'), ('Cloudy', 'Cloudy'), ('Windy', 'Windy')], default='Sunny', max_length=30)),
                ('special_event', models.CharField(choices=[('None', 'None'), ('Festival', 'Festival'), ('Sports Match', 'Sports Match'), ('Weekend Promo', 'Weekend Promo')], default='None', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='inventory_predictor.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='inventory_predictor.supplier'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Kitchen Manager'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wastage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('reason', models.CharField(choices=[('Expired', 'Expired'), ('Spoiled', 'Spoiled'), ('Over-preparation', 'Over-preparation'), ('Damaged', 'Damaged'), ('Other', 'Other')], default='Spoiled', max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastages', to='inventory_predictor.ingredient')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.FloatField(help_text='Amount of ingredient required per single menu item')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_items', to='inventory_predictor.ingredient')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory_predictor.menuitem')),
            ],
            options={
                'unique_together': {('menu_item', 'ingredient')},
            },
        ),
    ]
